
pipeline:
  checkout-master:
    image: plugin/git
    commands:
      - git fetch master
      - git checkout master
    when:
      event: push

  build:
    image: node:latest
    commands:
      - yarn install --frozen-lockfile

  coding-conventions:
    group: test
    image: node:latest
    commands:
      - yarn test:coding-conventions

  functional:
    group: test
    image: node:latest
    secrets: [ SAUCE_USERNAME, SAUCE_ACCESS_KEY ]
    commands:
      - yarn dist
      - yarn test:functional
